from typing import List, Tuple, overload

class ChadSelect:
    """Rust-powered unified data extraction.

    Supports Regex, XPath 1.0, CSS Selectors, and JMESPath queries.
    Queries complete in 100µs–3ms (pure Rust, no I/O).
    """

    def __init__(self) -> None: ...
    def add_text(self, content: str) -> None: ...
    def add_html(self, content: str) -> None: ...
    def add_json(self, content: str) -> None: ...
    def content_count(self) -> int: ...
    def clear(self) -> None: ...
    def query(self, index: int, query_str: str) -> List[str]: ...
    def select(self, index: int, query_str: str) -> str: ...
    def select_first(self, queries: List[Tuple[int, str]]) -> List[str]: ...
    def select_many(self, queries: List[Tuple[int, str]]) -> List[str]: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

class AsyncChadSelect:
    """Async wrapper around ChadSelect.

    Content loading is synchronous (instant). Query methods are async
    for API consistency — Rust execution is 100µs–3ms, so event-loop
    blocking is negligible.
    """

    def __init__(self) -> None: ...
    def add_text(self, content: str) -> None: ...
    def add_html(self, content: str) -> None: ...
    def add_json(self, content: str) -> None: ...
    def content_count(self) -> int: ...
    def clear(self) -> None: ...
    async def query(self, index: int, query_str: str) -> List[str]: ...
    async def select(self, index: int, query_str: str) -> str: ...
    async def select_first(self, queries: List[Tuple[int, str]]) -> List[str]: ...
    async def select_many(self, queries: List[Tuple[int, str]]) -> List[str]: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...

__version__: str
__all__: List[str]
